### ISSUE TITLE
Could we add a license file?

### ISSUE THREAD

**Issue by jonathankarsh** [f/omelette#16]
Hello and thanks for publishing this awesome project!
I was considering using this for a project and wanted to make sure I'm doing the right thing - but saw that there's no license file. I'm not sure if the (currently) single line at the end of the readme file applicable.
Would you accept a pull request with the MIT license?
Otherwise (from https://help.github.com/articles/adding-a-license-to-a-repository/), looks like you can manually add a license file to the repo.
Regards
Jonathan

**Comment by f** [comment]
Here you are!

**Comment by jonathankarsh** [comment]
Awesome! Much appreciated
