### ISSUE TITLE
Add uninstall script

### ISSUE THREAD

**Issue by Loilo** [f/omelette#29]
It would be immensely useful to have a counterpart to `setupShellInitFile()`, something like `cleanupShellInitFile()`.

That would allow to run `setupShellInitFile()` in an npm `postinstall` hook. Doing this right now will append another completion block to the shell init file each time `npm i -g cli-package` is run (e.g. to update the CLI).

`cleanupShellInitFile()` could be used in a `postuninstall` hook to make sure there will never be more than one completion block.

**Comment by RWOverdijk** [comment]
Good idea. I was looking for this :)

**Comment by Loilo** [comment]
FWIW, I used omelette to create a zero-config [autocomplete library](https://github.com/Loilo/completarr) for yargs. I wrote the necessary uninstall script myself, so if you're in need of one: [here it is](https://github.com/Loilo/completarr/blob/master/src/uninstall).

Would still love to see this in omelette itself. Would give a little more safety regarding updates.

**Comment by f** [comment]
Wow that's awesome. I will put it inside omelette ASAP, thank you! (Wish
you'd open a PR)

26 Eyl 2018 Çar 17:50 tarihinde Florian Reuschel <notifications@github.com>
şunu yazdı:

**Comment by Loilo** [comment]
Let me set up an alarm clock, and I'll get back to that. 😉
