### ISSUE TITLE
rfc: dynamic lookups

### ISSUE THREAD

**Issue by cdaringe** [f/omelette#41]
# problem

i want to conditionally add more tabbables based on previous lookups

# discussion

imagine:

```
const completion = omelette(`bestbin <root>`)

completion.on('root', ({ reply }) => {
  return reply([ 'a', 'b' ])
})

completion.on('b', ({ reply }) => {
  return reply(['c'])
})

completion.on('c', ({ reply }) => {
  return reply(['--d'])
})

completion.on('e', ({ reply }) => {
  return reply(['f'])
})
```

my args don't have a fixed length, so the `bin <cmd> <structure> <of> <fixed> <arity>` doesn't work for me. is this something you'd support?

**Comment by f** [comment]
actually you can already get previous data.

```
const completion = omelette(`bestbin <root>`)

completion.on('root', ({ reply }) => {
  return reply([ 'a', 'b' ])
})

completion.on('b', ({ before, reply }) => {
  // before will be "a" or "b"
  return reply(['c'])
})
```

And you can also use "complete" event to watch globally:
https://github.com/f/omelette#global-event

```
complete.on('complete', (fragment, { before, reply }) => reply(["hello", "world"]));

// fragment is the current part,
// before is previous data
// reply is replier
```

**Comment by cdaringe** [comment]
Cool, thank you. I thought that I had tried it and failed, but perhaps I need to reinvestigate. :-)

**Comment by cdaringe** [comment]
@f, i tried again, and indeed, in your example, then callback in `completion.on('b', cb)` never gets triggered:

```js
const completion = omelette(`bestbin <root>`)
completion.on('root', ({ reply }) => {
  return reply([ 'a', 'b' ])
})
completion.on('b', ({ before, reply }) => {
  return reply(['c'])
})
completion.init()
```

completion for `a` and `b` gets announced, but indeed, never does the b handler trigger
